### ISSUE TITLE
Article Spelling mistake

### ISSUE THREAD

**Issue by Na-ir** [itechf-s/fincz#7]
जिसमे jisse
हैंअखिरत
खेती किसानी में इन्वेस्टमेंट kisan kheti mai investment q karta hain
कुछ फल निकलेगा miss-nhin 
डाल bo raha hain
तालीम यानी कि पढ़ाई लिखाई pr investmentkarna
 के Extra
 
 वक्त जरूरत jarurat ke waqat kam ayega
 चुके है इन्वेस्टमेंट miss ki 
 इन्वेस्टमेंट तो होही जाता है।
  इसी तरह अगर किसी के सामने अच्छा बीज जमीन में नहीं डाला और उसके बाद भी उसकी देखभाल नहीं की तो उसको कुछ भी हासिल नहीं होता शिवाय उसकी
  जैसे हमारे पास ₹100 हो और पूरा पैसा हम इन्वेस्ट कर दें
  डालना है  bo na hain
  आप रूल खर्ची
  अब उसको कैसे करना है miss investment 
  अपनी स्किन skill
  तुल्य खर्चा पूरा करने
  फिजूलखर्ची रोके fizulkhazre

**Comment by itechf-s** [comment]
Issue Fixed
